apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: $NAMESPACE
  namespace: $NAMESPACE
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    ci-event:
      endpoint: /
      method: POST
      port: "12000"