apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
  name: $NAMESPACE
  namespace: $NAMESPACE
spec:
  rules:
    - host: $WEBHOOK_DOMAIN
      http:
        paths:
          - backend:
              service:
                name: $NAMESPACE
                port:
                  number: 12000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - $WEBHOOK_DOMAIN
      secretName: letsencrypt-tls