apiVersion: v1
data:
  argocd-server: aHR0cHM6Ly8xMC4wLjE3OC44Mg==
  password: cGFzc3dvcmQ=
  username: YWRtaW4=
kind: Secret
metadata:
  name: argocd-config
  namespace: $NAMESPACE

---

apiVersion: v1
data:
  config.json: eyJhdXRocyI6eyJ5b3VyLnJlZ2lzdGVyLmRvbWFpbi5jb20iOnsiYXV0aCI6ImRYTmxjbTVoYldVNmNHRnpjM2R2Y21RPSJ9fX0=
kind: Secret
metadata:
  name: docker-config
  namespace: $NAMESPACE

---

apiVersion: v1
data:
  private-key: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KLi4uCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQ==
kind: Secret
metadata:
  name: git-ssh-key
  namespace: $NAMESPACE
type: Opaque