apiVersion: v1
data:
  argocd-server: $ARGO_CD_SERVER
  password: $ARGO_CD_PASSWORD
  username: $ARGO_CD_USERNAME
kind: Secret
metadata:
  name: argocd-config
  namespace: $NAMESPACE

---

apiVersion: v1
data:
  config.json: $DOCKER_CONFIG
kind: Secret
metadata:
  name: docker-config
  namespace: $NAMESPACE

---

apiVersion: v1
data:
  private-key: $GIT_SSH_KEY
kind: Secret
metadata:
  name: git-ssh-key
  namespace: $NAMESPACE
type: Opaque