apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $NAMESPACE-workflow-role
  namespace: $NAMESPACE
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: $NAMESPACE-workflow-role-binding
  namespace: $NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: $NAMESPACE-workflow-role
subjects:
  - kind: ServiceAccount
    name: $NAMESPACE